/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifpb.ads.view;

import ifpb.ads.control.Controler_Funcionario;
import ifpb.ads.dto.FuncionarioDTO;
import ifpb.ads.view.factoryControl.FactoryFuncionario;
import ifpb.ads.view.factoryControl.ITfactory;
import javax.swing.JOptionPane;

/**
 *
 * @author italo
 */
public class Frm_login extends javax.swing.JFrame {

    /**
     * Creates new form bfxh
     */
    private Controler_Funcionario controleFuncionario;
    private ITfactory fabricaFuncionario;

    public Frm_login() {
        initComponents();
        fabricaFuncionario = new FactoryFuncionario();
        controleFuncionario = (Controler_Funcionario) fabricaFuncionario.gerar("control");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        area_cpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_acessar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        comboCargos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(76, 76, 76));
        jPanel1.setLayout(null);

        try {
            area_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.####.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(area_cpf);
        area_cpf.setBounds(150, 130, 200, 30);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Cargo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 70, 60, 20);

        bt_acessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifpb/ads/icones/iconfinder_Login_in_85205_1.png"))); // NOI18N
        bt_acessar.setText("Acessar");
        bt_acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_acessarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_acessar);
        bt_acessar.setBounds(81, 220, 110, 33);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifpb/ads/icones/iconfinder_Login_out_85206.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel1.add(btSair);
        btSair.setBounds(260, 220, 80, 30);

        comboCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendente", "Recepcionista", "Gerente" }));
        jPanel1.add(comboCargos);
        comboCargos.setBounds(156, 70, 190, 40);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("CPF");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 130, 26, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifpb/ads/icones/background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(467, 320));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_acessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_acessarActionPerformed
        // TODO add your handling code here:
        FuncionarioDTO logado = (FuncionarioDTO) fabricaFuncionario.gerar("dto");
        try {
            String cpf = area_cpf.getText();
            String cargo = (String) comboCargos.getSelectedItem();

            if (cpf.equals("111.1111.111-11")) {
                logado.setName("MASTER");
                new Frm_inicial(logado).setVisible(true);
                dispose();
            } else {
                logado = controleFuncionario.acessSistem(cpf, cargo);
                if (logado.getId() > 0) {
                    new Frm_inicial(logado).setVisible(true);
                    dispose();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao acessar o sistema. " + e.getMessage());
        }
    }//GEN-LAST:event_bt_acessarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        controleFuncionario.fecharConexoes();
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField area_cpf;
    private javax.swing.JButton btSair;
    private javax.swing.JButton bt_acessar;
    private javax.swing.JComboBox<String> comboCargos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
